import {
  ArrowUpRight,
  Bot,
  BrainCircuit,
  CheckCircle2,
  GitMerge,
  MoreHorizontal,
  Plus,
  Search,
  SlidersHorizontal,
  Sparkles,
  Tag,
  Tags,
  WandSparkles,
  Zap,
  type LucideIcon,
} from "lucide-react";

import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

type BadgeVariant = "success" | "warning" | "danger" | "neutral" | "info";
type TagType = "Manual" | "AI" | "Automation";
type TagSection = "Lead Tags" | "Contact Tags" | "Campaign Tags" | "AI Auto Tags";

type TagItem = {
  id: string;
  name: string;
  color: string;
  type: TagType;
  section: TagSection;
  usageCount: number;
  createdBy: string;
  lastUsed: string;
};

type Kpi = {
  label: string;
  value: string;
  trend: string;
  helper: string;
  icon: LucideIcon;
  variant: BadgeVariant;
};

type SuggestionGroup = {
  title: string;
  icon: LucideIcon;
  variant: BadgeVariant;
  items: string[];
};

const kpis: Kpi[] = [
  {
    label: "Total Tags",
    value: "248",
    trend: "+18",
    helper: "Across CRM records",
    icon: Tags,
    variant: "success",
  },
  {
    label: "Auto Tags",
    value: "64",
    trend: "+22.4%",
    helper: "Generated by AI and rules",
    icon: WandSparkles,
    variant: "info",
  },
  {
    label: "Hot Lead Tags",
    value: "31",
    trend: "High intent",
    helper: "Used in active sales queues",
    icon: Sparkles,
    variant: "warning",
  },
  {
    label: "Unused Tags",
    value: "19",
    trend: "Cleanup",
    helper: "No usage in 90 days",
    icon: GitMerge,
    variant: "neutral",
  },
];

const tagItems: TagItem[] = [
  {
    id: "tag-501",
    name: "Hot Lead",
    color: "#ef4444",
    type: "Automation",
    section: "Lead Tags",
    usageCount: 1842,
    createdBy: "Revenue Ops",
    lastUsed: "4 min ago",
  },
  {
    id: "tag-502",
    name: "Follow-up Needed",
    color: "#f59e0b",
    type: "Automation",
    section: "Lead Tags",
    usageCount: 932,
    createdBy: "AI Rules",
    lastUsed: "12 min ago",
  },
  {
    id: "tag-503",
    name: "Enterprise Buyer",
    color: "#38bdf8",
    type: "Manual",
    section: "Contact Tags",
    usageCount: 486,
    createdBy: "Priya Nair",
    lastUsed: "1 hour ago",
  },
  {
    id: "tag-504",
    name: "VIP Customer",
    color: "#a78bfa",
    type: "Manual",
    section: "Contact Tags",
    usageCount: 264,
    createdBy: "Customer Success",
    lastUsed: "Today",
  },
  {
    id: "tag-505",
    name: "Demo Offer",
    color: "#10b981",
    type: "Manual",
    section: "Campaign Tags",
    usageCount: 1294,
    createdBy: "Marketing",
    lastUsed: "22 min ago",
  },
  {
    id: "tag-506",
    name: "Retargeting Cohort",
    color: "#22c55e",
    type: "Automation",
    section: "Campaign Tags",
    usageCount: 756,
    createdBy: "Growth Team",
    lastUsed: "Yesterday",
  },
  {
    id: "tag-507",
    name: "Price Sensitive",
    color: "#fb7185",
    type: "AI",
    section: "AI Auto Tags",
    usageCount: 388,
    createdBy: "AI Classifier",
    lastUsed: "8 min ago",
  },
  {
    id: "tag-508",
    name: "High Intent WhatsApp",
    color: "#14b8a6",
    type: "AI",
    section: "AI Auto Tags",
    usageCount: 612,
    createdBy: "AI Classifier",
    lastUsed: "18 min ago",
  },
];

const suggestions: SuggestionGroup[] = [
  {
    title: "Tags to merge",
    icon: GitMerge,
    variant: "warning",
    items: ["Hot", "Hot Lead", "High Intent"],
  },
  {
    title: "Tags used most",
    icon: Tags,
    variant: "success",
    items: ["Hot Lead", "Demo Offer", "Follow-up Needed"],
  },
  {
    title: "Recommended for automation",
    icon: Bot,
    variant: "info",
    items: ["Price Sensitive", "No Reply", "High Intent WhatsApp"],
  },
];

const labelRules = [
  {
    condition: "If lead score > 80",
    result: "Hot Lead",
    owner: "AI Scoring",
    status: "Active",
  },
  {
    condition: "If no reply in 3 days",
    result: "Follow-up Needed",
    owner: "Engagement Rules",
    status: "Active",
  },
  {
    condition: "If demo booked",
    result: "Demo Booked",
    owner: "Calendar Sync",
    status: "Active",
  },
];

const sections: TagSection[] = ["Lead Tags", "Contact Tags", "Campaign Tags", "AI Auto Tags"];

const typeVariant: Record<TagType, BadgeVariant> = {
  Manual: "neutral",
  AI: "info",
  Automation: "success",
};

function KpiCard({ item }: { item: Kpi }) {
  const Icon = item.icon;

  return (
    <Card>
      <CardContent className="p-5">
        <div className="flex items-center justify-between">
          <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-400/10 text-emerald-300">
            <Icon className="h-5 w-5" />
          </span>
          <Badge variant={item.variant}>
            <ArrowUpRight className="h-3 w-3" />
            {item.trend}
          </Badge>
        </div>
        <p className="mt-5 text-sm text-slate-400">{item.label}</p>
        <h2 className="mt-1 text-3xl font-bold tracking-tight text-white">{item.value}</h2>
        <p className="mt-2 text-sm text-slate-500">{item.helper}</p>
      </CardContent>
    </Card>
  );
}

function FilterControl({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <label className="grid gap-2">
      <span className="text-xs font-semibold uppercase tracking-wide text-slate-500">
        {label}
      </span>
      {children}
    </label>
  );
}

function TagCard({ item }: { item: TagItem }) {
  return (
    <article className="rounded-2xl border border-white/10 bg-black/10 p-4 transition hover:border-emerald-400/30">
      <div className="flex items-start justify-between gap-3">
        <div className="flex min-w-0 items-center gap-3">
          <span
            className="h-4 w-4 shrink-0 rounded-full ring-4 ring-white/10"
            style={{ backgroundColor: item.color }}
          />
          <div className="min-w-0">
            <h3 className="truncate font-semibold text-white">{item.name}</h3>
            <p className="mt-1 text-xs text-slate-500">{item.id}</p>
          </div>
        </div>
        <Button variant="ghost" size="icon" aria-label={`Open ${item.name} actions`}>
          <MoreHorizontal className="h-4 w-4" />
        </Button>
      </div>

      <div className="mt-4 grid gap-3">
        <div className="flex items-center justify-between gap-3">
          <span className="text-sm text-slate-500">Type</span>
          <Badge variant={typeVariant[item.type]}>{item.type}</Badge>
        </div>
        <div className="flex items-center justify-between gap-3">
          <span className="text-sm text-slate-500">Usage count</span>
          <span className="text-sm font-semibold text-white">{item.usageCount.toLocaleString()}</span>
        </div>
        <div className="flex items-center justify-between gap-3">
          <span className="text-sm text-slate-500">Created by</span>
          <span className="text-sm text-slate-300">{item.createdBy}</span>
        </div>
        <div className="flex items-center justify-between gap-3">
          <span className="text-sm text-slate-500">Last used</span>
          <span className="text-sm text-slate-300">{item.lastUsed}</span>
        </div>
      </div>
    </article>
  );
}

export default function TagsLabelsModule() {
  return (
    <div className="flex min-h-screen bg-[#07111f] text-white">
      <Sidebar />
      <main className="min-w-0 flex-1">
        <Topbar eyebrow="CRM" title="Tags & Labels" />

        <section className="space-y-6 p-4 md:p-6 lg:p-8">
          <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
            <div>
              <Badge variant="info">Segmentation system</Badge>
              <h1 className="mt-4 text-3xl font-bold tracking-tight text-white md:text-4xl">
                Tags & Labels
              </h1>
              <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400 md:text-base">
                Govern CRM taxonomy, automate labels, clean duplicate segments, and keep
                revenue teams aligned around consistent lead and customer signals.
              </p>
            </div>

            <Button className="w-full sm:w-auto">
              <Plus className="h-4 w-4" />
              Create Tag
            </Button>
          </div>

          <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-4">
            {kpis.map((item) => (
              <KpiCard key={item.label} item={item} />
            ))}
          </div>

          <Card>
            <CardHeader>
              <div className="flex items-start gap-3">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-400/10 text-emerald-300">
                  <SlidersHorizontal className="h-5 w-5" />
                </span>
                <div>
                  <CardTitle>Tag Filters</CardTitle>
                  <CardDescription>
                    Find tags by name, creation type, and usage pattern.
                  </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4 md:grid-cols-3">
                <FilterControl label="Search tag">
                  <div className="relative">
                    <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
                    <input
                      type="search"
                      placeholder="Tag name, creator, rule..."
                      className="h-11 w-full rounded-lg border border-white/10 bg-white/5 pl-10 pr-3 text-sm text-white outline-none placeholder:text-slate-500 focus:border-emerald-400/60 focus:ring-2 focus:ring-emerald-400/20"
                    />
                  </div>
                </FilterControl>

                <FilterControl label="Type filter">
                  <select className="h-11 rounded-lg border border-white/10 bg-[#0b1628] px-3 text-sm text-white outline-none focus:border-emerald-400/60 focus:ring-2 focus:ring-emerald-400/20">
                    <option>All types</option>
                    <option>Manual</option>
                    <option>AI</option>
                    <option>Automation</option>
                  </select>
                </FilterControl>

                <FilterControl label="Usage filter">
                  <select className="h-11 rounded-lg border border-white/10 bg-[#0b1628] px-3 text-sm text-white outline-none focus:border-emerald-400/60 focus:ring-2 focus:ring-emerald-400/20">
                    <option>All usage</option>
                    <option>High usage</option>
                    <option>Recently used</option>
                    <option>Unused</option>
                  </select>
                </FilterControl>
              </div>
            </CardContent>
          </Card>

          <div className="grid gap-6 2xl:grid-cols-12">
            <div className="space-y-6 2xl:col-span-9">
              {sections.map((section) => {
                const sectionTags = tagItems.filter((item) => item.section === section);

                return (
                  <Card key={section}>
                    <CardHeader>
                      <div>
                        <CardTitle>{section}</CardTitle>
                        <CardDescription>
                          {sectionTags.length} managed labels for this CRM surface.
                        </CardDescription>
                      </div>
                      <Badge variant="neutral">{sectionTags.length} tags</Badge>
                    </CardHeader>
                    <CardContent>
                      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                        {sectionTags.map((item) => (
                          <TagCard key={item.id} item={item} />
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>

            <div className="space-y-6 2xl:col-span-3">
              <Card className="border-emerald-500/20 bg-emerald-500/10">
                <CardHeader>
                  <div className="flex items-start gap-3">
                    <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-400/10 text-emerald-300">
                      <BrainCircuit className="h-5 w-5" />
                    </span>
                    <div>
                      <CardTitle>AI Suggestions</CardTitle>
                      <CardDescription>
                        Merge, usage, and automation recommendations.
                      </CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  {suggestions.map((group) => {
                    const Icon = group.icon;

                    return (
                      <div key={group.title} className="rounded-xl bg-black/20 p-4">
                        <div className="flex items-center justify-between gap-3">
                          <div className="flex items-center gap-2">
                            <Icon className="h-4 w-4 text-emerald-300" />
                            <p className="text-sm font-semibold text-white">{group.title}</p>
                          </div>
                          <Badge variant={group.variant}>{group.items.length}</Badge>
                        </div>
                        <div className="mt-3 flex flex-wrap gap-2">
                          {group.items.map((item) => (
                            <Badge key={`${group.title}-${item}`} variant="neutral">
                              {item}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    );
                  })}
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <div className="flex items-start gap-3">
                    <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-400/10 text-sky-300">
                      <Zap className="h-5 w-5" />
                    </span>
                    <div>
                      <CardTitle>Label Rules</CardTitle>
                      <CardDescription>Automation logic for consistent labeling.</CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-3">
                  {labelRules.map((rule) => (
                    <div key={rule.condition} className="rounded-xl border border-white/10 bg-black/10 p-4">
                      <div className="flex items-start gap-3">
                        <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" />
                        <div>
                          <p className="text-sm font-semibold text-white">{rule.condition}</p>
                          <p className="mt-2 text-sm text-slate-300">Then apply: {rule.result}</p>
                          <div className="mt-3 flex flex-wrap gap-2">
                            <Badge variant="success">{rule.status}</Badge>
                            <Badge variant="neutral">{rule.owner}</Badge>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <div className="flex items-start gap-3">
                    <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-400/10 text-amber-300">
                      <Tag className="h-5 w-5" />
                    </span>
                    <div>
                      <CardTitle>Governance Notes</CardTitle>
                      <CardDescription>Controls for enterprise tag hygiene.</CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-3">
                  {[
                    "Archive unused tags after review instead of deleting historical context.",
                    "Require approval for global automation labels.",
                    "Merge similar high-usage tags during monthly taxonomy cleanup.",
                  ].map((item) => (
                    <div key={item} className="rounded-xl bg-black/10 p-3 text-sm leading-6 text-slate-300">
                      {item}
                    </div>
                  ))}
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
