"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, Kanban, List, Loader2, Plus, Search, Table2, Trash2, Users } from "lucide-react";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";

type Tag = { id: string; name: string; color: string | null };
type Stage = { id: string; name: string; color: string | null; probability: number };
type User = { id: string; name: string | null; email: string };
type Lead = { id: string; firstName: string | null; lastName: string | null; title: string; email: string | null; phone: string | null; source: string | null; status: string; score: number; value: string | null; notes: string | null; updatedAt: string; assignedUser: User | null; company: { name: string } | null; stage: Stage | null; tags: Tag[]; leadMemory: { summary: string | null; requirement: string | null; budget: string | null; timeline: string | null } | null; _count: { inboxConversations: number; tasks: number } };
type Payload = { leads: Lead[]; stages: Stage[]; tags: Tag[]; users: User[] };

const input = "h-10 rounded-lg border border-white/10 bg-[#0b1628] px-3 text-sm text-white outline-none focus:border-emerald-400/60";
const button = "inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-white/10 bg-white/5 px-3 text-sm font-medium text-slate-200 hover:bg-white/10 disabled:opacity-40";

export default function LeadsModule({ initialView = "table" }: { initialView?: "list" | "table" | "kanban" }) {
  const [data, setData] = useState<Payload>({ leads: [], stages: [], tags: [], users: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState("");
  const [view, setView] = useState<"list" | "table" | "kanban">(initialView); const [selected, setSelected] = useState<string[]>([]);
  const load = useCallback(async () => { setLoading(true); const res = await fetch(`/api/crm?search=${encodeURIComponent(search)}`, { cache: "no-store" }); const body = await res.json(); if (!res.ok) setError(body.error ?? "Unable to load leads."); else { setData(body); setError(""); } setLoading(false); }, [search]);
  useEffect(() => { const timer = setTimeout(load, 200); return () => clearTimeout(timer); }, [load]);
  async function mutate(action: string, extra: Record<string, unknown> = {}, ids = selected) { if (!ids.length) return; const res = await fetch("/api/crm", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ids, ...extra }) }); const body = await res.json(); if (!res.ok) setError(body.error); else { setSelected([]); await load(); } }
  async function remove() { if (!selected.length || !confirm(`Delete ${selected.length} selected lead(s)?`)) return; const res = await fetch("/api/crm", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: selected }) }); if (res.ok) { setSelected([]); await load(); } }
  async function createTag() { const tagName = prompt("Tag name"); if (!tagName?.trim()) return; const color = prompt("Tag color (hex)", "#38bdf8") || "#38bdf8"; const res = await fetch("/api/crm", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "createTag", name: tagName, color }) }); const body = await res.json(); if (!res.ok) setError(body.error); else await load(); }
  function exportCsv() { const rows = data.leads.filter(l => !selected.length || selected.includes(l.id)); const csv = [["Name","Mobile","Email","Company","Source","Stage","Budget","Requirement","Timeline","Owner"], ...rows.map(l => [name(l),l.phone,l.email,l.company?.name,l.source,l.stage?.name,l.leadMemory?.budget,l.leadMemory?.requirement,l.leadMemory?.timeline,l.assignedUser?.name ?? l.assignedUser?.email].map(csvCell))].map(r => r.join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = `rdleadify-leads-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(a.href); }
  const totalValue = useMemo(() => data.leads.reduce((n,l) => n + Number(l.value ?? 0), 0), [data.leads]);
  return <div className="flex min-h-screen bg-[#07111f] text-white"><Sidebar/><main className="min-w-0 flex-1"><Topbar eyebrow="CRM" title="Leads"/><section className="space-y-5 p-4 md:p-6 lg:p-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Leads CRM</h1><p className="mt-2 text-sm text-slate-400">Live customer records, memory, ownership, tags and pipeline movement.</p></div><div className="flex gap-2"><button onClick={createTag} className={button}><Plus className="h-4 w-4"/>Create tag</button><a href="/ai-agent" className={`${button} border-emerald-400/30 bg-emerald-400/10 text-emerald-300`}><Plus className="h-4 w-4"/>Capture lead</a></div></div>
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Total leads" value={data.leads.length}/><Metric label="Pipeline value" value={new Intl.NumberFormat("en-US", { style:"currency", currency:"USD", maximumFractionDigits:0 }).format(totalValue)}/><Metric label="Needs assignment" value={data.leads.filter(l=>!l.assignedUser).length}/></div>
    <div className="rounded-xl border border-white/10 bg-white/[.035] p-3"><div className="flex flex-wrap gap-2"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, phone, email..." className={`${input} w-full pl-10`}/></label>{(["list","table","kanban"] as const).map((v,i)=>{const I=[List,Table2,Kanban][i];return <button key={v} onClick={()=>setView(v)} className={`${button} ${view===v?"border-emerald-400/40 text-emerald-300":""}`}><I className="h-4 w-4"/><span className="capitalize">{v}</span></button>})}</div>
    {selected.length>0&&<div className="mt-3 flex flex-wrap items-center gap-2 border-t border-white/10 pt-3"><span className="text-sm text-emerald-300">{selected.length} selected</span><select className={input} defaultValue="" onChange={e=>e.target.value&&mutate("assign",{assignedUserId:e.target.value})}><option value="">Assign…</option>{data.users.map(u=><option key={u.id} value={u.id}>{u.name??u.email}</option>)}</select><select className={input} defaultValue="" onChange={e=>e.target.value&&mutate("tag",{tagId:e.target.value})}><option value="">Add tag…</option>{data.tags.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select className={input} defaultValue="" onChange={e=>e.target.value&&mutate("move",{stageId:e.target.value})}><option value="">Move pipeline…</option>{data.stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className={button} onClick={exportCsv}><Download className="h-4 w-4"/>Export</button><button className={`${button} text-rose-300`} onClick={remove}><Trash2 className="h-4 w-4"/>Delete</button></div>}</div>
    {error&&<div className="rounded-lg border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</div>}
    {loading?<div className="grid place-items-center py-24 text-slate-400"><Loader2 className="mb-3 h-7 w-7 animate-spin"/>Loading CRM…</div>:data.leads.length===0?<Empty/>:view==="kanban"?<Board data={data} mutate={mutate}/>:<LeadRows leads={data.leads} selected={selected} setSelected={setSelected} compact={view==="list"}/>}
  </section></main></div>;
}
function name(l: Lead){return [l.firstName,l.lastName].filter(Boolean).join(" ")||l.title} function csvCell(v: unknown){return `"${String(v??"").replaceAll('"','""')}"`}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-white/10 bg-white/[.035] p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
function TagPill({tag}:{tag:Tag}){return <span className="rounded-full border px-2 py-0.5 text-xs" style={{borderColor:`${tag.color??"#64748b"}66`,color:tag.color??"#94a3b8"}}>{tag.name}</span>}
function LeadRows({leads,selected,setSelected,compact}:{leads:Lead[];selected:string[];setSelected:(v:string[])=>void;compact:boolean}){return <div className="overflow-x-auto rounded-xl border border-white/10 bg-white/[.025]"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase text-slate-500"><tr><th className="p-4"><input type="checkbox" checked={selected.length===leads.length} onChange={e=>setSelected(e.target.checked?leads.map(l=>l.id):[])}/></th>{["Lead","Contact","Source","Tags","Pipeline","Owner","AI memory","Last activity"].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{leads.map(l=><tr key={l.id} className="border-b border-white/5 hover:bg-white/[.03]"><td className="p-4"><input type="checkbox" checked={selected.includes(l.id)} onChange={e=>setSelected(e.target.checked?[...selected,l.id]:selected.filter(x=>x!==l.id))}/></td><td className="p-4"><p className="font-semibold">{name(l)}</p><p className="text-xs text-slate-500">{l.company?.name??l.title}</p></td><td className="p-4 text-slate-300"><p>{l.phone??"—"}</p><p className="text-xs text-slate-500">{l.email??"No email"}</p></td><td className="p-4">{l.source??"Manual"}</td><td className="p-4"><div className="flex max-w-44 flex-wrap gap-1">{l.tags.map(t=><TagPill key={t.id} tag={t}/>)}</div></td><td className="p-4"><span style={{color:l.stage?.color??"#94a3b8"}}>{l.stage?.name??l.status}</span></td><td className="p-4">{l.assignedUser?.name??l.assignedUser?.email??"Unassigned"}</td><td className="max-w-64 p-4 text-slate-400">{l.leadMemory?.summary??l.notes?.split("\n")[0]??"No summary yet"}{!compact&&l.leadMemory?.requirement&&<p className="mt-1 text-xs text-slate-500">Needs: {l.leadMemory.requirement}</p>}</td><td className="p-4 text-slate-400">{new Date(l.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
function Board({data,mutate}:{data:Payload;mutate:(a:string,e:Record<string,unknown>,ids:string[])=>Promise<void>}){return <div className="flex gap-4 overflow-x-auto pb-4">{data.stages.map(s=><section key={s.id} onDragOver={e=>e.preventDefault()} onDrop={e=>mutate("move",{stageId:s.id},[e.dataTransfer.getData("leadId")])} className="min-h-[420px] w-72 shrink-0 rounded-xl border border-white/10 bg-white/[.025] p-3"><div className="mb-3 flex justify-between"><b style={{color:s.color??"white"}}>{s.name}</b><span className="text-xs text-slate-500">{data.leads.filter(l=>l.stage?.id===s.id||(!l.stage&&s.name==="New Lead")).length}</span></div>{data.leads.filter(l=>l.stage?.id===s.id||(!l.stage&&s.name==="New Lead")).map(l=><article draggable onDragStart={e=>e.dataTransfer.setData("leadId",l.id)} key={l.id} className="mb-2 cursor-grab rounded-lg border border-white/10 bg-[#0b1628] p-3"><b>{name(l)}</b><p className="mt-1 text-xs text-slate-400">{l.leadMemory?.requirement??l.source??"Manual"}</p><div className="mt-2 flex flex-wrap gap-1">{l.tags.slice(0,2).map(t=><TagPill key={t.id} tag={t}/>)}</div></article>)}</section>)}</div>}
function Empty(){return <div className="grid place-items-center rounded-xl border border-dashed border-white/15 py-24 text-center"><Users className="h-9 w-9 text-slate-600"/><h2 className="mt-4 font-semibold">No leads found</h2><p className="mt-1 text-sm text-slate-500">Captured AI, widget and API leads will appear here.</p></div>}
