"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Bot, CheckCircle2, Inbox, Loader2, Search, Send } from "lucide-react";
import Sidebar from "@/components/Sidebar"; import Topbar from "@/components/Topbar";
type User={id:string;name:string|null;email:string}; type Message={id:string;sender:string;text:string|null;timestamp:string;aiGenerated:boolean};
type Conversation={id:string;customerName:string|null;customerPhone:string|null;customerEmail:string|null;channel:string;lastMessage:string|null;lastMessageTime:string|null;unreadCount:number;status:string;tags:string[];aiSummary:string|null;assignedUser:User|null;lead:{id:string;stage:{name:string}|null;tags:{name:string;color:string|null}[]}|null;messages?:Message[]};
const control="h-10 rounded-lg border border-white/10 bg-[#0b1628] px-3 text-sm text-white outline-none focus:border-emerald-400/60";
export default function InboxModule(){const [items,setItems]=useState<Conversation[]>([]),[users,setUsers]=useState<User[]>([]),[active,setActive]=useState<string>(),[detail,setDetail]=useState<Conversation>(),[loading,setLoading]=useState(true),[reply,setReply]=useState(""),[search,setSearch]=useState(""),[channel,setChannel]=useState("ALL"),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/inbox",{cache:"no-store"}),b=await r.json();if(r.ok){setItems(b.conversations);setUsers(b.users);setActive(current=>current??b.conversations[0]?.id);if(!active&&b.conversations[0]?.id){const d=await fetch(`/api/inbox?id=${b.conversations[0].id}`,{cache:"no-store"}),db=await d.json();if(d.ok)setDetail(db.conversations[0])}}else setError(b.error);setLoading(false)},[active]);
 // State changes happen after user selection or awaited network responses; this is not a synchronous effect update.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 const open=useCallback(async(id:string)=>{setActive(id);const r=await fetch(`/api/inbox?id=${id}`,{cache:"no-store"}),b=await r.json();if(r.ok){setDetail(b.conversations[0]);await mutateRaw({action:"read",id});setItems(x=>x.map(c=>c.id===id?{...c,unreadCount:0}:c))}},[]); useEffect(()=>{load()},[load]);
 async function mutateRaw(body:Record<string,unknown>){const r=await fetch("/api/inbox",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)setError(b.error);return r.ok}
 async function mutate(action:string,extra:Record<string,unknown>={}){if(!active)return;if(await mutateRaw({action,id:active,...extra})){await load();await open(active)}} async function send(){const text=reply.trim();if(!text)return;setReply("");await mutate("reply",{text})}
 const filtered=useMemo(()=>items.filter(c=>(channel==="ALL"||c.channel===channel)&&`${c.customerName} ${c.customerPhone} ${c.customerEmail} ${c.lastMessage}`.toLowerCase().includes(search.toLowerCase())),[items,channel,search]); const channels=["ALL",...Array.from(new Set(items.map(i=>i.channel)))];
 return <div className="flex min-h-screen bg-[#07111f] text-white"><Sidebar/><main className="min-w-0 flex-1"><Topbar eyebrow="Omnichannel" title="Universal Inbox"/><div className="grid min-h-[calc(100vh-73px)] lg:grid-cols-[360px_minmax(0,1fr)_300px]">
 <aside className="border-r border-white/10"><div className="space-y-3 border-b border-white/10 p-4"><label className="relative block"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500"/><input className={`${control} w-full pl-10`} placeholder="Search conversations…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="flex gap-2 overflow-x-auto">{channels.map(c=><button key={c} onClick={()=>setChannel(c)} className={`shrink-0 rounded-full px-3 py-1 text-xs ${channel===c?"bg-emerald-400 text-slate-950":"bg-white/5 text-slate-400"}`}>{label(c)}</button>)}</div></div>
 {loading?<Loader/>:<div className="max-h-[calc(100vh-180px)] overflow-y-auto">{filtered.map(c=><button key={c.id} onClick={()=>open(c.id)} className={`w-full border-b border-white/5 p-4 text-left hover:bg-white/[.04] ${active===c.id?"bg-emerald-400/[.08]":""}`}><div className="flex justify-between gap-3"><b className="truncate">{c.customerName??c.customerPhone??"Unknown customer"}</b>{c.unreadCount>0&&<span className="grid h-5 min-w-5 place-items-center rounded-full bg-emerald-400 px-1 text-xs font-bold text-slate-950">{c.unreadCount}</span>}</div><p className="mt-1 truncate text-sm text-slate-400">{c.lastMessage??"No messages"}</p><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{label(c.channel)}</span><span>{relative(c.lastMessageTime)}</span></div></button>)}{!filtered.length&&<div className="p-8 text-center text-sm text-slate-500">No conversations found.</div>}</div>}</aside>
 <section className="flex min-h-[600px] flex-col">{detail?<><header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 p-4"><div><h2 className="font-semibold">{detail.customerName??detail.customerPhone??"Unknown customer"}</h2><p className="text-xs text-slate-500">{label(detail.channel)} · {detail.customerPhone??detail.customerEmail??"No contact detail"}</p></div><div className="flex gap-2"><select className={control} value={detail.status} onChange={e=>mutate("status",{status:e.target.value})}>{["OPEN","PENDING","RESOLVED","LOST","SPAM"].map(s=><option key={s}>{s}</option>)}</select><select className={control} value={detail.assignedUser?.id??""} onChange={e=>mutate("assign",{assignedUserId:e.target.value||null})}><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.name??u.email}</option>)}</select></div></header><div className="flex-1 space-y-3 overflow-y-auto p-5">{detail.messages?.map(m=><div key={m.id} className={`flex ${m.sender==="CUSTOMER"?"justify-start":"justify-end"}`}><div className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm ${m.sender==="CUSTOMER"?"bg-white/[.07]":"bg-emerald-400 text-slate-950"}`}><p>{m.text??"Attachment"}</p><p className={`mt-1 text-[10px] ${m.sender==="CUSTOMER"?"text-slate-500":"text-slate-700"}`}>{m.sender}{m.aiGenerated?" · AI":""} · {new Date(m.timestamp).toLocaleString()}</p></div></div>)}</div><div className="border-t border-white/10 p-4"><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.035] p-2"><input className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none" placeholder="Write a reply…" value={reply} onChange={e=>setReply(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey)send()}}/><button onClick={send} className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-400 text-slate-950"><Send className="h-4 w-4"/></button></div></div></>:<div className="grid flex-1 place-items-center text-slate-500"><div className="text-center"><Inbox className="mx-auto h-10 w-10"/><p className="mt-3">Select a conversation</p></div></div>}</section>
 <aside className="border-l border-white/10 p-5"><h3 className="flex items-center gap-2 font-semibold"><Bot className="h-4 w-4 text-emerald-300"/>AI customer memory</h3><p className="mt-3 text-sm leading-6 text-slate-400">{detail?.aiSummary??"AI summary will appear as the conversation develops."}</p><div className="mt-5 space-y-4 text-sm"><Info k="Pipeline" v={detail?.lead?.stage?.name??"Not qualified"}/><Info k="Assigned user" v={detail?.assignedUser?.name??detail?.assignedUser?.email??"Unassigned"}/><Info k="Last activity" v={detail?.lastMessageTime?new Date(detail.lastMessageTime).toLocaleString():"—"}/><div><p className="text-xs uppercase text-slate-500">Tags</p><div className="mt-2 flex flex-wrap gap-1">{[...(detail?.tags??[]),...(detail?.lead?.tags.map(t=>t.name)??[])].map(t=><span key={t} className="rounded-full bg-white/[.07] px-2 py-1 text-xs">{t}</span>)}</div></div>{detail?.status==="RESOLVED"&&<p className="flex gap-2 text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Conversation resolved</p>}</div>{error&&<p className="mt-5 text-sm text-rose-300">{error}</p>}</aside>
 </div></main></div>}
function Info({k,v}:{k:string;v:string}){return <div><p className="text-xs uppercase text-slate-500">{k}</p><p className="mt-1 text-slate-200">{v}</p></div>} function Loader(){return <div className="grid place-items-center py-20 text-slate-500"><Loader2 className="h-6 w-6 animate-spin"/></div>} function label(s:string){return s.replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,x=>x.toUpperCase())} function relative(v:string|null){if(!v)return"—";const m=Math.floor((Date.now()-new Date(v).getTime())/60000);return m<1?"Now":m<60?`${m}m`:m<1440?`${Math.floor(m/60)}h`:`${Math.floor(m/1440)}d`}
